var map,oms,polyarray=[],markarray=[],infoarray=[],accesstoken,infowindow=new google.maps.InfoWindow,genquery,nSearches,delay=1,baseurl,userID;google.maps.event.addDomListener(window,"load",initialize);
function initialize(){var a={zoom:3,center:new google.maps.LatLng(30,-30),streetViewControl:!1,panControl:!1,zoomControl:!0,zoomControlOptions:{style:google.maps.ZoomControlStyle.DEFAULT,position:google.maps.ControlPosition.LEFT_BOTTOM}};map=new google.maps.Map(document.getElementById("mapdisplay"),a);oms=new OverlappingMarkerSpiderfier(map,{keepSpiderfied:!0,nearbyDistance:35});mc=new MarkerClusterer(map,[],{maxZoom:4,gridSize:20,zoomOnClick:!0,styles:[{url:"images/band2.png",height:46,width:46,
anchor:[8,0],textSize:12,textColor:"#000000"}]});populateUser()}function ancestorgens(){clearOverlays();startEvents();var a=document.getElementById("genSelect");genquery=parseFloat(a.value);getPedigree(genquery,void 0,void 0)}function ancestorExpand(a,d,b){startEvents();genquery=1;getPedigree(1,a,d,b)}
function getPedigree(a,d,b,g){d=d?d:document.getElementById("personid").value;d=baseurl+"pedigree/"+d+"?ancestors="+a+"&properties=all&sessionId="+accesstoken;var h;h=new XMLHttpRequest;h.open("GET",d);h.onload=function(d){if(4===h.readyState)if(200===h.status){d=h.responseXML.documentElement.getElementsByTagName("person");var c=[];c[0]=d[0].getAttribute("id");for(var k=0;k<Math.pow(2,a)-1;k++)if(d[k]){var f=d[k].getElementsByTagName("parent");1<f.length?(c[2*(k+1)-1]=f[0].getAttribute("id"),c[2*
(k+1)]=f[1].getAttribute("id")):(c[2*(k+1)-1]=void 0,c[2*(k+1)]=void 0)}else c[2*(k+1)-1]=void 0,c[2*(k+1)]=void 0;readPedigreeLoop(c,b,g)}else completionEvents(),alert("Error: "+h.statusText)};h.send()}
function readPedigreeLoop(a,d,b){var g=!0,h;delay=1;var e=a.length,c=[];d||(d=0);asyncLoop(e,function(e){var f=e.iteration(),l=a[f];l?personRead(l,function(a){if(a)if(503==a)e.prev(),e.next();else{c[f]=a;c[f].generation=Math.ceil(log2(f+2))-1+d;0==f?c[f].isPaternal=b:1==f&&1==c[f].generation?c[f].isPaternal=!0:2==f&&1==c[f].generation?c[f].isPaternal=!1:"Male"==c[f].gender?c[(f+1)/2-1]&&(c[f].isPaternal=c[(f+1)/2-1].isPaternal):c[f/2-1]&&(c[f].isPaternal=c[f/2-1].isPaternal);var l=h?h:c[f].birth.place;
setTimeout(function(){getLatLng(l,function(a){c[f].birth.latlng=a;"empty"==a?(delay++,e.prev(),e.next()):"other"==a?(a=l.split(","),!0==g?(h=a[0]+","+a[a.length-1],g=!1,e.prev(),e.next()):(console.log('Unable to find location "'+c[f].birth.place+'" for '+c[f].name+" ("+c[f].id+")"),c[f].birth.latlng=getChildBirthPlace(c,f),g=!0,h=void 0,callLoopNext(e,c))):(a||(console.log("Undefined birthplace for "+c[f].name+" ("+c[f].id+")"),c[f].birth.latlng=getChildBirthPlace(c,f)),g=!0,h=void 0,callLoopNext(e,
c))})},delay)}else c[f]=void 0,callLoopNext(e,c)}):(c[f]=void 0,callLoopNext(e,c))},function(){})}
function personRead(a,d){var b=baseurl+"person/"+a+"?&events=standard&sessionId="+accesstoken,g;g=new XMLHttpRequest;g.open("GET",b);g.onload=function(b){if(4===g.readyState)if(200===g.status){b=g.responseXML.documentElement;var e=b.getElementsByTagName("fullText");if(e[0])var c=e[0].textContent;""==a&&(e=b.getElementsByTagName("person"),e[0]&&(a=e[0].getAttribute("id")));e=b.getElementsByTagName("gender");if(e[0])var k=e[0].textContent;b=b.getElementsByTagName("events");if(b[0]&&(e=b[0].getElementsByTagName("value"),
"Birth"==e[0].getAttribute("type"))){b=e[0].getElementsByTagName("date");e=e[0].getElementsByTagName("place");if(e[0])var f=e[0].childNodes[1]?e[0].childNodes[1].textContent:e[0].childNodes[0].textContent;if(b[0])var l=b[0].childNodes[1]?b[0].childNodes[1].textContent:b[0].childNodes[0].textContent}d({name:c,id:a,birth:{date:l,place:f},gender:k})}else 503!=g.status?(completionEvents(),alert("Error: "+g.statusText)):d(g.status)};g.send()}
function getLatLng(a,d){a?(new google.maps.Geocoder).geocode({address:a},function(a,g){g==google.maps.GeocoderStatus.OK?d(a[0].geometry.location):g==google.maps.GeocoderStatus.OVER_QUERY_LIMIT?d("empty"):d("other")}):d(a)}function callLoopNext(a,d){var b=a.iteration();log2(b+2)==Math.round(log2(b+2))?0!==b?checkBounds(d,a):a.next():a.next()}
function checkBounds(a,d){new google.maps.LatLngBounds;var b=map.getBounds();!0==firstTime&&(makeInfoWindow(a[0]),firstTime=!1);for(var g=0;g<a.length;g++)a[g]&&a[g].birth.latlng&&!1==b.contains(a[g].birth.latlng)&&(b.extend(a[g].birth.latlng),map.fitBounds(b));plotNextGeneration(a,d)}
function plotNextGeneration(a,d){var b=d.iteration(),g=log2(b+2)-1;loadingAnimationEnd();for(var h=Math.pow(2,g),b=h-1;b<2*h-1;b++){var e=[];a[b]&&(e[1]=a[b].birth.latlng);var c=b,c=isEven(b+1)?(b+1)/2-1:c/2-1;a[c]&&(e[0]=a[c].birth.latlng);a[b]?!0==a[b].isPaternal?polymap(e,rgbToHex(74,96,255),"",b,function(b){makeInfoWindow(a[b]);b==2*h-2&&(g!==genquery?loadingAnimationStart():completionEvents(),d.next())}):polymap(e,rgbToHex(255,96,182),"",b,function(b){makeInfoWindow(a[b]);b==2*h-2&&(g!==genquery?
loadingAnimationStart():completionEvents(),d.next())}):b==2*h-2&&(g!==genquery?loadingAnimationStart():completionEvents(),d.next())}}function polymap(a,d,b,g,h){var e=a[0],c=a[1];if(e&&c){var k=new google.maps.Polyline({strokeColor:d,strokeOpacity:1,strokeWeight:3,geodesic:!0,path:[e,e],map:map});polyarray.push(k);var f=0,l=setInterval(function(){f+=1;if(250<f)clearInterval(l),h(g);else{var a=google.maps.geometry.spherical.interpolate(e,c,f/250);k.setPath([e,a])}},1)}else h(g)}
function makeInfoWindow(a){if(a&&a.birth.latlng){if("Male"==a.gender)var d="lightblue",b="images/male"+a.generation+".png";else d="pink",b="images/female"+a.generation+".png";b={map:map,position:a.birth.latlng,icon:{url:b,origin:new google.maps.Point(0,0),anchor:new google.maps.Point(11.5,14)}};b=new google.maps.Marker(b);b.idx=markarray.length;a.generation>genquery-1?(b.expand="<button class='greenbutton' onclick='this.style.display=\"none\"; markarray["+b.idx+'].isExpanded=true; ancestorExpand("'+
a.id+'",'+a.generation+","+a.isPaternal+"); infowindow.close();'>EXPAND</button>",b.isExpanded=!1):(b.isExpanded=!0,b.expand="");var g="<button class='bluebutton' style=\"width:100px\" onclick='populateIdField(\""+a.id+"\")'>"+a.id+"</button></div>";b.content1="<div id='infow' style='background-color:"+d+"'>"+a.name+"<br/>"+a.birth.place+"<br/>"+a.birth.date+"<br/>";b.content2=g;oms.addListener("click",function(a,b){a.isExpanded?infowindow.setContent(a.content1+a.content2):infowindow.setContent(a.content1+
a.expand+a.content2);infowindow.open(map,a)});mc.addMarker(b);oms.addListener("spiderfy",function(a){infowindow.close()});oms.addMarker(b);markarray.push(b)}}function getChildBirthPlace(a,d){if("Male"==a[d].gender){if(a[(d+1)/2-1])return a[(d+1)/2-1].birth.latlng}else if(a[d/2-1])return a[d/2-1].birth.latlng}
function asyncLoop(a,d,b){var g=0,h=!1,e={next:function(){h||(g<a?(g++,d(e)):(h=!0,b()))},prev:function(){g--},iteration:function(){return g-1},breakout:function(){h=!0;b()}};e.next();return e}function loadingAnimationStart(){$(function(){$("#loading").show()});$(function(){$("#loading").activity({segments:10,width:3,space:1,length:6,color:"#FFFFFF",speed:1.5})})}function loadingAnimationEnd(){$(function(){$("#loading").activity(!1)});$(function(){$("#loading").hide()})}
function clearOverlays(){for(var a=0;a<markarray.length;a++)markarray[a].setMap(null);for(a=0;a<polyarray.length;a++)polyarray[a].setMap(null);markarray.length=0;polyarray.length=0;firstTime=!0;nSearches=0;oms.clearMarkers();mc.clearMarkers()}function componentToHex(a){a=a.toString(16);return 1==a.length?"0"+a:a}function rgbToHex(a,d,b){return"#"+componentToHex(a)+componentToHex(d)+componentToHex(b)}function populateIdField(a){document.getElementById("personid").value=a}
function populateUser(){userID?populateIdField(userID):personRead("",function(a){populateIdField(a.id);userID=a.id;document.getElementById("username").value=a.name})}function isEven(a){return a/2==Math.round(a/2)?!0:!1}function log2(a){return Math.log(a)/Math.log(2)}function startEvents(){loadingAnimationStart();var a=document.getElementById("runButton");a.disabled=!0;a.className="disabledbutton"}
function completionEvents(){loadingAnimationEnd();var a=document.getElementById("runButton");a.disabled=!1;a.className="runButton"};
